// GENERATED by scripts/capture-samples.mjs. Do not edit.
//
// Each entry is the structuredContent the real server returned to tools/call over stdio,
// with the arguments it was called with and when it ran. Nothing here was typed by hand.
export const SAMPLES_SERVER = {
 "name": "openlookup",
 "version": "0.5.1"
} as const;
export const SAMPLES = [
 {
  "tool": "compare_ai_models",
  "args": {
   "board": "budget/value",
   "limit": 3
  },
  "ran_at": "2026-10-05T19:57:02.896Z",
  "ms": 758,
  "result": {
   "board": "budget/value",
   "captured_on": "2026-10-05",
   "method_summary": "Ranks adoption — how much a model is actually run inside the tracked coding tools. Does not measure capability. No benchmark is involved. A cheap model can lead on volume alone. Blended USD per million tokens, weighting prompt to completion 3:1, because coding traffic is prompt-heavy.",
   "method_url": "https://tooldrift.thecompound.tech/method",
   "available_boards": [
    "budget/balanced",
    "budget/free",
    "budget/premium",
    "budget/value",
    "overall/all",
    "tool/aider",
    "tool/claude-code",
    "tool/cline",
    "tool/codex-cli",
    "tool/codex-cloud",
    "tool/kilo-code",
    "tool/roo-code"
   ],
   "models": [
    {
     "rank": 1,
     "model": "z-ai/glm-5.3-flash",
     "score": 58.44,
     "blended_usd_per_mtok": 0.2375,
     "price_band": "Under $1 / M",
     "rationale": "11.93T tokens through 6 tracked coding tools · $0.24 per million tokens blended · Under $1 / M band · 1049K context. Ranked on usage, which measures adoption rather than capability."
    },
    {
     "rank": 2,
     "model": "deepseek/deepseek-v4.1-flash",
     "score": 43.54,
     "blended_usd_per_mtok": 0.525,
     "price_band": "Under $1 / M",
     "rationale": "4.81T tokens through 6 tracked coding tools · $0.53 per million tokens blended · Under $1 / M band · 1049K context. Ranked on usage, which measures adoption rather than capability."
    },
    {
     "rank": 3,
     "model": "nvidia/nemotron-3-ultra-550b-a55b",
     "score": 24.43,
     "blended_usd_per_mtok": 0.925,
     "price_band": "Under $1 / M",
     "rationale": "3.05T tokens through 5 tracked coding tools · $0.93 per million tokens blended · Under $1 / M band · 262K context. Ranked on usage, which measures adoption rather than capability."
    }
   ],
   "browse": "https://tooldrift.thecompound.tech"
  }
 },
 {
  "tool": "lookup_ada_report",
  "args": {
   "domain": "36thdistrictcourtmi.gov"
  },
  "ran_at": "2026-10-05T19:57:03.655Z",
  "ms": 285,
  "result": {
   "found": true,
   "domain": "36thdistrictcourtmi.gov",
   "entity_name": "36th District Court",
   "entity_type": "City",
   "city": "Detroit",
   "state": "MI",
   "population": 645705,
   "grade": "A",
   "grade_meaning": "no serious or critical failures detected",
   "violations_total": 0,
   "violations_serious": 0,
   "violations_critical": 0,
   "top_rules": [],
   "ada_title_ii_deadline": "2027-04-26",
   "deadline_label": "April 26, 2027 (communities of 50,000+)",
   "url_scanned": "https://www.36thdistrictcourtmi.gov/",
   "scanned_at": "2026-08-01T11:15:23.632+00:00",
   "axe_version": "4.12.1",
   "pages_scanned": 1,
   "report_url": "https://civicbinder.org/ada/36thdistrictcourtmi.gov",
   "checked": {
    "at": "2026-10-05T19:57:03.939Z",
    "sources": [
     "CivicBinder Municipal Web Accessibility Index (axe-core, WCAG 2.1 AA)"
    ],
    "via": "https://xowekqdsttxwbhfxvusa.supabase.co/rest/v1/cb_ada_scans",
    "scope": "Covers US local-government websites that the index has scanned. The grade describes the pages listed in pages_scanned as they were on scanned_at, not the site as it stands now, and an automated scan cannot establish WCAG conformance on its own."
   }
  }
 },
 {
  "tool": "estimate_stack_cost",
  "args": {
   "stack": "supabase,clerk,polar,vercel",
   "users": 10000
  },
  "ran_at": "2026-10-05T19:57:03.940Z",
  "ms": 602,
  "result": {
   "stack": [
    "supabase",
    "clerk",
    "polar",
    "vercel"
   ],
   "unknown_services": [],
   "users": 10000,
   "monthly_total_usd": 315,
   "unpriced_services": [],
   "services": [
    {
     "service": "Supabase",
     "plan": "Pro",
     "monthly_usd": 25,
     "lines": [
      {
       "label": "Pro base",
       "detail": "flat monthly fee",
       "usd": 25
      },
      {
       "label": "Monthly active users",
       "detail": "10,000 MAU stays within the included 100,000.",
       "usd": 0
      },
      {
       "label": "Database disk",
       "detail": "5 GB-db stays within the included 8.",
       "usd": 0
      },
      {
       "label": "File storage",
       "detail": "10 GB-storage stays within the included 100.",
       "usd": 0
      },
      {
       "label": "Egress",
       "detail": "200 GB-egress stays within the included 250.",
       "usd": 0
      }
     ]
    },
    {
     "service": "Clerk",
     "plan": "Free",
     "monthly_usd": 0,
     "lines": [
      {
       "label": "Free base",
       "detail": "no monthly fee",
       "usd": 0
      }
     ]
    },
    {
     "service": "Polar",
     "plan": "Pro",
     "monthly_usd": 270,
     "lines": [
      {
       "label": "Pro base",
       "detail": "flat monthly fee",
       "usd": 20
      },
      {
       "label": "Rate on revenue",
       "detail": "3.8% of $4,000",
       "usd": 152
      },
      {
       "label": "Per transaction",
       "detail": "200 transactions × $0.4",
       "usd": 80
      },
      {
       "label": "International cards",
       "detail": "1.5% of $1,200 (30% of revenue)",
       "usd": 18
      }
     ]
    },
    {
     "service": "Vercel",
     "plan": "Pro",
     "monthly_usd": 20,
     "lines": [
      {
       "label": "Pro base",
       "detail": "flat monthly fee",
       "usd": 20
      },
      {
       "label": "Edge requests",
       "detail": "2 req-1M stays within the included 10.",
       "usd": 0
      },
      {
       "label": "Fast data transfer",
       "detail": "200 GB-egress stays within the included 1,000.",
       "usd": 0
      },
      {
       "label": "Function invocations",
       "detail": "0.5 inv-1M stays within the included 1.",
       "usd": 0
      },
      {
       "label": "Function duration",
       "detail": "55.56 GB-hr stays within the included 420.",
       "usd": 0
      },
      {
       "label": "Seats",
       "detail": "1 seat stays within the included 1.",
       "usd": 0
      }
     ]
    }
   ],
   "browse": "https://stacktab.thecompound.tech"
  }
 },
 {
  "tool": "check_project_maintenance",
  "args": {
   "limit": 3
  },
  "ran_at": "2026-10-05T19:57:04.542Z",
  "ms": 891,
  "result": {
   "query": "(recently declared dead)",
   "results": [
    {
     "name": "MetaGPT",
     "status": "dead",
     "last_release": "2025-03-09T15:59:39+00:00",
     "last_commit": "2026-01-21T10:12:33+00:00",
     "stars": 70342,
     "url": "https://atoms.dev/"
    },
    {
     "name": "get-shit-done",
     "status": "dead",
     "last_release": "2026-05-17T16:11:16+00:00",
     "last_commit": "2026-05-31T17:46:54+00:00",
     "stars": 64543,
     "url": "https://github.com/gsd-build/get-shit-done"
    },
    {
     "name": "Flowise",
     "status": "dead",
     "last_release": "2026-07-29T15:51:25+00:00",
     "last_commit": "2026-08-13T12:38:19+00:00",
     "stars": 55456,
     "url": "https://flowiseai.com"
    }
   ],
   "browse": "https://stillshipping.thecompound.tech"
  }
 },
 {
  "tool": "lookup_nonprofit_status",
  "args": {
   "ein": "475262842"
  },
  "ran_at": "2026-10-05T19:57:05.433Z",
  "ms": 309,
  "result": {
   "ein": "475262842",
   "clear": true,
   "message": "EIN 475262842 does not appear on the IRS auto-revocation list or the California registry delinquency/suspension lists that GoodStanding tracks. On those lists, this organization reads as in good standing. Full check: https://goodstanding.thecompound.tech/#lookup",
   "checked": {
    "at": "2026-10-05T19:57:05.742Z",
    "sources": [
     "IRS Automatic Revocation of Exemption List",
     "California Attorney General Registry of Charities and Fundraisers"
    ],
    "via": "https://goodstanding.thecompound.tech/api/lookup",
    "scope": "Covers only the two lists named above, as GoodStanding retains them. A clear result means the EIN is absent from those lists. It is not a statement that the organization was never revoked, and no other state registry is consulted."
   }
  }
 },
 {
  "tool": "compare_app_builders",
  "args": {
   "limit": 4
  },
  "ran_at": "2026-10-05T19:57:05.742Z",
  "ms": 510,
  "result": {
   "total": 14,
   "verdict_vocabulary": {
    "ships": "A documented path to a submitted binary on your own Apple Developer account.",
    "ships-with-caveats": "Reaches the App Store, but the last mile happens outside the tool or a named guideline is in play.",
    "blocked": "Does not produce something submittable to the App Store at all.",
    "unknown": "No source found that settles it. Unproven, not failed."
   },
   "builders": [
    {
     "builder": "Rork",
     "slug": "rork",
     "verdict": "ships-with-caveats",
     "why": "Produces a real Expo binary and markets App Store shipping as the headline outcome, and the export path means a failed one-click publish is recoverable rather than terminal. The caveat is that the strongest claims here are the vendor’s own marketing and third-party reviews rather than a submission-record document — and the Rork Max Swift path is new enough as of August 2026 that it has no review history to read.",
     "output": "react-native-expo",
     "exports_source": "yes",
     "who_submits": "builder-assisted",
     "app_store_guidelines_in_play": [
      "4.2"
     ],
     "free_tier": true,
     "price_from_usd": 20,
     "updated_at": "2026-09-04T14:09:55.863+00:00"
    },
    {
     "builder": "Vibecode",
     "slug": "vibecode",
     "verdict": "ships",
     "why": "The clearest documented path in the catalogue. Vibecode’s own deployment page requires you to hold the $99/year Apple Developer Program membership and sign the agreements yourself, which is exactly the arrangement guideline 4.2.6 asks for — the app is submitted by the party whose content it is, not by the generator. It also ships a preflight check aimed at the mechanical rejection causes (icons, metadata, configuration).",
     "output": "react-native-expo",
     "exports_source": "unknown",
     "who_submits": "you-submit",
     "app_store_guidelines_in_play": [
      "4.2"
     ],
     "free_tier": null,
     "price_from_usd": 20,
     "updated_at": "2026-09-04T14:09:55.865+00:00"
    },
    {
     "builder": "a0.dev",
     "slug": "a0-dev",
     "verdict": "unknown",
     "why": "No document, listing or dated report was found that establishes what happens when an a0.dev app is submitted. The team is described as helping users get to the App Store, which is an intention rather than a record. This row stays unknown until there is something citable — a builder with no evidence is not the same as a builder with bad evidence, and the grid should not blur them.",
     "output": "react-native-expo",
     "exports_source": "unknown",
     "who_submits": "builder-assisted",
     "app_store_guidelines_in_play": [],
     "free_tier": false,
     "price_from_usd": 20,
     "updated_at": "2026-09-04T14:09:55.865+00:00"
    },
    {
     "builder": "Replit Mobile",
     "slug": "replit",
     "verdict": "ships",
     "why": "Replit documents the arrangement that matters: it prepares the app and walks you through submission, but the Apple Developer account is yours and the binary goes through ordinary App Review. That keeps the submitter and the content provider the same party, which is the hinge guideline 4.2.6 turns on. The mobile product is new as of early 2026, so there is a documented path but not yet a long public record of outcomes.",
     "output": "react-native-expo",
     "exports_source": "yes",
     "who_submits": "builder-assisted",
     "app_store_guidelines_in_play": [
      "4.2"
     ],
     "free_tier": false,
     "price_from_usd": 20,
     "updated_at": "2026-09-04T14:09:55.865+00:00"
    }
   ],
   "browse": "https://storeready.thecompound.tech"
  }
 }
];
