#!/usr/bin/env node
/* CAPTURE REAL ANSWERS FROM THE SERVER ITSELF, FOR THE SIMPLE VIEW.
 *
 *   node scripts/capture-samples.mjs
 *
 * capture.mjs freezes the catalogue and calls nothing. The Simple view also shows what a tool
 * hands back, and an answer typed by hand is a fabricated record. So this spawns the same binary
 * over stdio and calls a few tools with the arguments the package's own README and argument
 * descriptions use, then freezes each tool's structuredContent, with the moment it ran, into
 * src/lib/samples.ts. Every tool here is an unauthenticated GET against a public endpoint: no key
 * is read and nothing is written.
 *
 * Fails closed: a call that errors, or answers without structuredContent, writes nothing. */
import { spawn } from 'node:child_process';
import { existsSync, writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const PKG_DIR = process.env.COMPOUND_MCP_DIR || resolve(ROOT, '..', 'compound-mcp');
const OUT = resolve(ROOT, 'src/lib/samples.ts');
if (!existsSync(resolve(PKG_DIR, 'bin/openlookup.js'))) throw new Error(`the package is not at ${PKG_DIR}. Set COMPOUND_MCP_DIR.`);

/* The calls. Arguments come from the README's Examples section and the tools' own argument text. */
const CALLS = [
  { tool: 'compare_ai_models', args: { board: 'budget/value', limit: 3 } },
  { tool: 'lookup_ada_report', args: { domain: '36thdistrictcourtmi.gov' } },
  { tool: 'estimate_stack_cost', args: { stack: 'supabase,clerk,polar,vercel', users: 10000 } },
  { tool: 'check_project_maintenance', args: { limit: 3 } },
  { tool: 'lookup_nonprofit_status', args: { ein: '475262842' } },
  { tool: 'compare_app_builders', args: { limit: 4 } },
];

const p = spawn(process.execPath, ['bin/openlookup.js'], { cwd: PKG_DIR, stdio: ['pipe', 'pipe', 'pipe'] });
const send = (o) => p.stdin.write(JSON.stringify(o) + '\n');
const waiting = new Map();
let buf = '';
p.stdout.on('data', (d) => {
  buf += d.toString();
  const lines = buf.split('\n');
  buf = lines.pop() ?? '';
  for (const line of lines) {
    let m;
    try { m = JSON.parse(line); } catch { continue; }
    const w = waiting.get(m.id);
    if (w) { waiting.delete(m.id); w(m); }
  }
});
let id = 0;
const call = (method, params) =>
  new Promise((done, bad) => {
    const n = ++id;
    const t = setTimeout(() => bad(new Error(`${method} timed out`)), 45_000);
    waiting.set(n, (m) => {
      clearTimeout(t);
      if (m.error) bad(new Error(JSON.stringify(m.error)));
      else done(m.result);
    });
    send({ jsonrpc: '2.0', id: n, method, params });
  });

try {
  const init = await call('initialize', { protocolVersion: '2025-06-18', capabilities: {}, clientInfo: { name: 'openlookup-site samples', version: '1' } });
  send({ jsonrpc: '2.0', method: 'notifications/initialized' });
  const out = [];
  for (const c of CALLS) {
    const started = Date.now();
    const r = await call('tools/call', { name: c.tool, arguments: c.args });
    if (r.isError) throw new Error(`${c.tool} answered with an error: ${JSON.stringify(r.content).slice(0, 300)}`);
    if (!r.structuredContent) throw new Error(`${c.tool} answered without structuredContent`);
    out.push({ tool: c.tool, args: c.args, ran_at: new Date(started).toISOString(), ms: Date.now() - started, result: r.structuredContent });
    console.log(`ok  ${c.tool}  ${Date.now() - started}ms`);
  }
  const body =
    `// GENERATED by scripts/capture-samples.mjs. Do not edit.\n` +
    `//\n` +
    `// Each entry is the structuredContent the real server returned to tools/call over stdio,\n` +
    `// with the arguments it was called with and when it ran. Nothing here was typed by hand.\n` +
    `export const SAMPLES_SERVER = ${JSON.stringify(init.serverInfo, null, 1)} as const;\n` +
    `export const SAMPLES = ${JSON.stringify(out, null, 1)};\n`;
  writeFileSync(OUT, body);
  console.log(`wrote ${OUT}`);
} finally {
  p.kill();
}
