#!/usr/bin/env node
/* Vendors the Phosphor Regular glyphs THIS site draws, from the Phosphor core repo.
 *
 *   npm run icons
 *
 * From the source, never from another product's tree. A copy of a copy has no source to
 * re-read, and there is no shared component library in this estate to take one from: those
 * repos were purged on 2026-09-14 and every app vendors its own set.
 *
 * The glyphs compile into src/lib/phosphor.ts as path bodies in currentColor, so a glyph takes
 * the ink of whatever sits beside it. No icon font and no runtime CDN.
 */
import { writeFile, mkdir } from 'node:fs/promises';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const OUT = resolve(ROOT, 'vendor/phosphor');
const BASE = 'https://raw.githubusercontent.com/phosphor-icons/core/main/assets/regular';
const LICENSE = 'https://raw.githubusercontent.com/phosphor-icons/core/main/LICENSE';

/* One glyph per caller. A glyph with no caller is a glyph to delete rather than to keep in
 * case, so this list is the site's own and matches nothing in any sibling repo. */
const WANT = [
  'plugs-connected', // the tool surface, and the two transports
  'download-simple', // the install page
  'file-text', // the method page
  'caret-up-down', // the app switch beside the mark
  'caret-right', // a tool row that opens
  'copy', // the copy action on a command
  'terminal-window', // a command block, and the Console button of the view toggle
  'article', // the Simple button of the view toggle
  'brackets-curly', // the argument schema of a tool
  'globe-hemisphere-west', // the public endpoint a tool reads
  'clock-countdown', // the group whose answers go stale
  'books', // the directory group
  'seal-check', // the compliance group
  'check', // a required argument, an endpoint that answered
  'x', // an argument a tool rejects
  'prohibit', // no key, no signup, no account
  'warning-circle', // an unproven verdict, a stated limit
  'pulse', // the health probe
  'clock', // a read date
  'arrow-square-out', // an outward link
  'info', // a note in a rail
  'package', // the npm package
  'github-logo', // the repository
];

await mkdir(OUT, { recursive: true });
const index = {};
for (const name of WANT) {
  const url = `${BASE}/${name}.svg`;
  const r = await fetch(url);
  if (!r.ok) throw new Error(`HTTP ${r.status} on ${url}`);
  const svg = await r.text();
  const body = svg
    .replace(/<\?xml[\s\S]*?\?>/g, '')
    .replace(/<svg[^>]*>/, '')
    .replace(/<\/svg>\s*$/, '')
    .replace(/fill="#[0-9a-fA-F]{3,8}"/g, 'fill="currentColor"')
    .trim();
  await writeFile(resolve(OUT, `${name}.svg`), svg);
  index[name] = body;
  process.stdout.write(`${name.padEnd(24)} ${svg.length}b\n`);
}
const lic = await fetch(LICENSE);
if (!lic.ok) throw new Error(`HTTP ${lic.status} on the licence`);
await writeFile(resolve(OUT, 'LICENSE'), await lic.text());

await writeFile(
  resolve(ROOT, 'src/lib/phosphor.ts'),
  `// GENERATED by scripts/icons.mjs from ${BASE}\n` +
    `// Phosphor Icons, MIT. The licence is vendored at vendor/phosphor/LICENSE.\n` +
    `export const GLYPH: Record<string, string> = ${JSON.stringify(index, null, 1)};\n` +
    `export type GlyphName = keyof typeof GLYPH;\n`,
);
process.stdout.write(`\nwrote src/lib/phosphor.ts, ${WANT.length} glyphs\n`);
